# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fake_personal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fake_personal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61ke_personal.proto\x12\rfake_personal\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0c\x46\x61kePersonal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t2\x9f\x01\n\x13\x46\x61kePersonalService\x12?\n\x08Generate\x12\x16.google.protobuf.Empty\x1a\x1b.fake_personal.FakePersonal\x12G\n\x0eStreamGenerate\x12\x16.google.protobuf.Empty\x1a\x1b.fake_personal.FakePersonal0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fake_personal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAKEPERSONAL']._serialized_start=67
  _globals['_FAKEPERSONAL']._serialized_end=126
  _globals['_FAKEPERSONALSERVICE']._serialized_start=129
  _globals['_FAKEPERSONALSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
